name: Feature Request
description: Suggest a new feature for the plugin.
title: "[Feature Request] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please make sure someone else hasn't requested the same feature by going to the [issues page](https://github.com/ffxivcode/AutoDuty/issues) and searching for a similar request.
  - type: textarea
    id: the-problem
    attributes:
      label: What problem are you trying to fix?
      description: Describe what the problem that you're trying to fix by creating this request. Please be clear and concise.
    validations:
      required: true
  - type: textarea
    id: the-solution
    attributes:
      label: What is the solution to the problem?
      description: Provide a description of what you want to change about the plugin's behavior.
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative solutions
      description: List some alternative solutions you are using or have considered using.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Please add any other context or screenshots pertaining to the feature request here.
