name: path-mdf-calc-onanychange
on:
  pull_request:
    types:
      - closed

env:
  BASE_BRANCH: md5-test

jobs:
  workflow:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: path-mdf-calc-onanychange
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files in the paths folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v45.0.3
        with:
          safe_output: "false"
          quotepath: "false"
          files: AutoDuty/Paths/**
          separator: ","

      - name: Calculate MD5 hashes and create JSON
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        id: calculate-md5
        run: |
          mkdir -p AutoDuty/Paths
          md5sum AutoDuty/Paths/* > md5sums.txt
          python -c "
          import json
          md5_dict = {}
          with open('md5sums.txt', 'r') as f:
              for line in f:
                  hash, filename = line.strip().split('  ')
                  md5_dict[filename] = hash
          with open('AutoDuty/Paths/mdfs.json', 'w') as f:
              json.dump(md5_dict, f, indent=4)
          "
          cat AutoDuty/Paths/mdfs.json

      - name: Commit changes to new branch
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b md5 origin/${{ env.BASE_BRANCH }}
          git add AutoDuty/Paths/mdfs.json
          git commit -m 'Add MD5 hashes for changed files'
          git push origin md5

      - name: Create pull request
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          PR_DATA=$(jq -n --arg title "Add MD5 hashes for changed files" --arg body "This PR adds MD5 hashes for the changed files in the AutoDuty/Paths folder." --arg head "md5" --arg base "${{ env.BASE_BRANCH }}" '{title: $title, body: $body, head: $head, base: $base}')
          curl -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/ffxivcode/AutoDuty/pulls -d "$PR_DATA"

      - name: Merge pull request
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          PR_NUMBER=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/ffxivcode/AutoDuty/pulls?head=ffxivcode:md5 | jq '.[0].number')
          curl -X PUT -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/ffxivcode/AutoDuty/pulls/$PR_NUMBER/merge -d '{"merge_method":"merge"}'

      - name: Delete branch
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          git push origin --delete md5
