name: Sync paths folder to S3
on:
  pull_request:
    types:
      - closed

jobs:
  checkout:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout paths folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'AutoDuty/Paths'
          sparse-checkout-cone-mode: false

      - name: Configure Git to handle non-ASCII characters
        run: git config --global core.quotePath false

      - name: Check if files are tracked by Git
        run: |
          find . -type f -print0 | xargs -0 -I {} bash -c '
            file="{}"
            if git ls-files --error-unmatch "$file" > /dev/null 2>&1; then
              echo "$file is tracked by Git."
            else
              echo "$file is not tracked by Git."
            fi
          '

      - name: Check commit history for each file
        run: |
          find . -type f -print0 | xargs -0 -I {} bash -c '
            file="{}"
            echo "Commit history for \"$file\":"
            git log -- "$file" || echo "No commits found for \"$file\""
          '

      - name: Update file timestamps to last commit time and echo timestamps
        run: |
          find . -type f -print0 | xargs -0 -I {} bash -c '
            file="{}"
            commit_time=$(git log -1 --format="%at" -- "$file")
            echo "Commit time for \"$file\": $commit_time"
            if [[ $commit_time =~ ^[0-9]+$ ]]; then
              touch -d "@$commit_time" "$file"
              echo "Updated timestamp for \"$file\": $(stat -c %y "$file")"
            else
              echo "Invalid commit time for \"$file\": $commit_time"
            fi
          '

      - name: Move paths folder files to root preserving timestamps
        run: |
          shopt -s dotglob
          rsync -a "AutoDuty/Paths/" .
          rm -rf AutoDuty

      - name: List files and folders
        run: |
          echo "Listing all files and folders in the base workspace directory:"
          ls -la

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-west-2

      - name: Sync paths folder to S3 bucket
        run: |
          aws s3 sync . s3://${{ secrets.AWS_BUCKET_NAME }}/ --delete --exclude ".github/*"
