name: checkout paths
on:
  push:
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout paths folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'AutoDuty/Paths'
          sparse-checkout-cone-mode: false
      - name: Move paths folder files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv AutoDuty/Paths/* .
          rm -rf AutoDuty
          ls -lah
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-west-2
      - name: Paths processing
        run: |
          FOLDER_PATH="/"
          BUCKET_NAME=${{ secrets.BUCKET_NAME }}
          for FILE_PATH in $FOLDER_PATH/*; do
            if [ -f "$FILE_PATH" ]; then
              FILE_NAME=$(basename "$FILE_PATH")
              OBJECT_KEY="$FILE_NAME"
              MD5_CHECKSUM=$(md5sum "$FILE_PATH" | awk '{ print $1 }')
              ETag=$(aws s3api head-object --bucket $BUCKET_NAME --key $OBJECT_KEY --query ETag --output text || echo "NOT_FOUND")
              ETag=${ETag//\"/}
              echo "checking $FILE_PATH md5: gh: $MD5_CHECKSUM s3: $ETag"
              if [ "$MD5_CHECKSUM" == "$ETag" ]; then
                echo "MD5 checksum matches ETag for $FILE_NAME. Skipping upload."
              else
                echo "MD5 checksum does not match ETag for $FILE_NAME or file not found. Uploading file."
                aws s3 cp "$FILE_PATH" "s3://$BUCKET_NAME/$OBJECT_KEY"
              fi
            fi
          done
