name: checkout paths
on:
  push:
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout paths folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'AutoDuty/Paths'
          sparse-checkout-cone-mode: false
      - name: Move paths folder files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv AutoDuty/Paths/* .
          rm -rf AutoDuty
          ls -lah
      - name: List files and folders
        run: |
          echo "Listing all files and folders in the base workspace directory:"
          ls -la
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-west-2
      - name: Delete any files in Paths that Match MD5
        run: |
          find . -type f ! -path "./.git/*" | while IFS= read -r file; do
            s3_key="${file#./}"
            if aws s3api head-object --bucket "${{ secrets.AWS_BUCKET_NAME }}" --key "$s3_key" >/dev/null 2>&1; then
              s3_etag=$(aws s3api head-object --bucket "${{ secrets.AWS_BUCKET_NAME }}" --key "$s3_key" --query ETag --output text | tr -d '"')
              md5_local=$(md5sum "$file" | awk '{ print $1 }')
              if [ "$md5_local" == "$s3_etag" ]; then
                echo "$file is up to date, deleting local file"
                rm "$file"
              fi
            fi
          done
      
      - name: Sync Path Files to S3
        run: |
          aws s3 sync . "s3://${{ secrets.AWS_BUCKET_NAME }}" --delete
