name: list changed-files
on:
  pull_request:
    types:
      - closed
jobs:
  workflow:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get changed files in the paths folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v45.0.3
        with:
          files: AutoDuty/Paths/**
      - name: Run step if any file(s) in the paths folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-specific.outputs.all_changed_files }}
        run: |
          echo "One or more files in the paths folder has changed."
          echo "List all the files that have changed: $ALL_CHANGED_FILES"
